package io.tenfold.app;
import android.app.*; import android.os.*; import android.content.*; import android.graphics.Color; import android.view.*; import android.widget.*;
public final class MainActivity extends Activity {
  SharedPreferences p; CycleState s; LinearLayout b; final int lime=Color.rgb(183,255,77);
  public void onCreate(Bundle x){super.onCreate(x);p=getSharedPreferences("tenfold",0);s=new CycleState(p);home();}
  void base(String title,String meta){ScrollView z=new ScrollView(this);b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(24,28,24,28);b.setBackgroundColor(Color.rgb(9,11,10));z.addView(b);setContentView(z);add("TENFOLD / TODAY ENDS, TOMORROW CONNECTS",11,lime);add(title,28,Color.WHITE);add(meta,13,Color.LTGRAY);}
  void add(String v,int n,int c){TextView t=new TextView(this);t.setText(v);t.setTextSize(n);t.setTextColor(c);t.setPadding(4,14,4,14);b.addView(t);}
  EditText input(String n,String v){add(n.toUpperCase(),11,lime);EditText e=new EditText(this);e.setText(v);e.setTextColor(Color.WHITE);b.addView(e);return e;}
  void go(String n,View.OnClickListener l){Button q=new Button(this);q.setText(n);q.setTextColor(Color.BLACK);q.setAllCaps(false);q.setBackgroundColor(lime);q.setOnClickListener(l);b.addView(q);}
  String mode(){return s.isSimulated()?"SIMULATED DEVICE · local demonstration":"USB PENDING ACK · device not confirmed";}
  void home(){if(p.getString("action","").isEmpty()){setup();return;}String phase=p.getString("phase","ACTIVE");if("RESUME_AVAILABLE".equals(phase)){resume();return;}if("AWAITING_NEXT_ACTION".equals(phase)){next();return;}base("今天到这里，明天接得上。",mode()+" · DEMO DAY "+s.demoDay()+"/10");add("TODAY\n"+p.getString("action",""),21,Color.WHITE);add("DONE WHEN\n"+p.getString("done",""),14,Color.LTGRAY);if(s.completed())add("TODAY IS ALREADY SAVED AS DONE.",14,lime);if(s.canComplete())go("确认：今天完成",v->{p.edit().putBoolean("completed",true).putString("phase","DONE").apply();home();});go("今天到这里",v->seal());go("DEMO TIME：进入下一天",v->{s.advanceDemoDay();home();});go("设置真实 LLM（可选）",v->settings());}
  void setup(){base("先留下一件承诺。","OFFLINE RULES · no LLM request was made");EditText g=input("十日想交付什么",""),st=input("今天卡在哪 / 剩余时间",""),a=input("今天做到哪就够",""),d=input("完成条件","");go("确认这张今日卡",v->{if(g.length()==0||a.length()==0||d.length()==0){toast("十日结果、动作和完成条件需要确认");return;}p.edit().putString("goal",g.getText().toString()).putString("stuck",st.getText().toString()).putString("action",a.getText().toString()).putString("done",d.getText().toString()).putString("phase","ACTIVE").putString("mode",CycleState.MODE_SIMULATED).apply();home();});}
  void seal(){base("先停下，不必假装完成。",mode());add(s.completed()?"完成事实会保留。":"未完成也能封存。",16,Color.WHITE);EditText n=input("停在哪（可选一句）",p.getString("stop_note",p.getString("stuck","")));go("保存并封存",v->{s.seal(n.getText().toString());toast("封存已保存；明天从这句话接回");home();});go("返回",v->home());}
  void resume(){base("昨天停在这里。",mode()+" · DEMO DAY "+s.demoDay());add("STOP NOTE\n"+s.stopNote(),17,Color.WHITE);add("FIRST STEP\n"+s.recoveryCard(),18,lime);go("确认接回这一步",v->{p.edit().putString("phase","ACTIVE").apply();home();});go("编辑恢复卡",v->next());}
  void next(){base("今天需要一张新卡。",mode());add("昨天已完成，不会自动重复计算。",16,Color.WHITE);EditText a=input("今天最小一步",""),d=input("新的完成条件","");go("确认新动作",v->{if(a.length()==0||d.length()==0){toast("请确认动作和完成条件");return;}p.edit().putString("action",a.getText().toString()).putString("done",d.getText().toString()).putString("phase","ACTIVE").apply();home();});}
  void settings(){base("可选真实 Agent 配置","未配置时仍是离线规则；不称 LLM 已调用。");EditText u=input("OpenAI-compatible endpoint",p.getString("llm_url","")),m=input("model",p.getString("llm_model","")),k=input("API key","");k.setInputType(129);go("仅保存到本机",v->{p.edit().putString("llm_url",u.getText().toString()).putString("llm_model",m.getText().toString()).putString("llm_key",k.getText().toString()).apply();toast("已本机保存；尚未发起调用");home();});}
  void toast(String x){Toast.makeText(this,x,Toast.LENGTH_LONG).show();}
}
