package io.tenfold.app;

import android.app.*; import android.os.*; import android.content.*; import android.content.SharedPreferences;
import android.graphics.Color; import android.hardware.usb.*; import android.view.*; import android.widget.*;
import java.nio.charset.StandardCharsets; import java.util.*; import org.json.*;

/** A deliberately offline-first P0: rules are not presented as an AI call. */
public final class MainActivity extends Activity {
  private LinearLayout screen; private TextView status; private SharedPreferences store; private UsbTransport usb;
  private final int lime=Color.rgb(183,255,77), ink=Color.rgb(9,11,10), panel=Color.rgb(21,26,23);
  @Override public void onCreate(Bundle b){super.onCreate(b); store=getSharedPreferences("tenfold",0); usb=new UsbTransport(this); showHome();}
  TextView text(String s,int size){ TextView v=new TextView(this); v.setText(s);v.setTextSize(size);v.setTextColor(Color.WHITE);v.setPadding(20,12,20,12);return v; }
  Button button(String s, View.OnClickListener l){ Button b=new Button(this);b.setText(s);b.setTextColor(Color.BLACK);b.setTextSize(14);b.setBackgroundColor(lime);b.setAllCaps(false);b.setOnClickListener(l);return b; }
  void base(String title){ ScrollView scroll=new ScrollView(this); screen=new LinearLayout(this);screen.setOrientation(LinearLayout.VERTICAL);screen.setPadding(22,28,22,28);screen.setBackgroundColor(ink);scroll.addView(screen);setContentView(scroll); TextView mark=text("TENFOLD  /  10-DAY FIELD SYSTEM",12);mark.setTextColor(lime);screen.addView(mark);screen.addView(text(title,29)); status=text("",13);status.setBackgroundColor(panel);screen.addView(status); }
  void showHome(){ base("今天，只留一件事。"); String phase=store.getString("phase","DRAFT"); boolean hardware=usb.findDevice()!=null;
    status.setText((hardware?"USB DEVICE DETECTED · REQUEST ACCESS TO CONNECT":"SIMULATED DEVICE · NO HARDWARE CLAIM")+"\nLOCAL STATE: "+phase+" · "+(hardware?"real transport available":"simulation clearly marked"));
    String action=store.getString("action",""); if(action.length()==0){screen.addView(text("把散乱输入压缩为一个可确认的十日承诺。规则引擎离线运行；它不是云端 LLM。",17));screen.addView(button("开始收敛",v->showCapture()));}
    else { screen.addView(text("TODAY / "+action,21)); screen.addView(text("DONE WHEN / "+store.getString("done","未设定"),14)); screen.addView(button("查看当前周期",v->showCycle())); }
    screen.addView(button(hardware?"连接 M5StickS3（USB）":"检查 USB 设备",v->{ usb.requestOrConnect(); showHome(); }));
  }
  void showCapture(){base("收集，不扩张。"); status.setText("LOCAL DRAFT · NO CLOUD DATA SENT"); final EditText input=new EditText(this);input.setHint("粘贴 1–10 条混乱任务，每行一条");input.setMinLines(7);input.setTextColor(Color.WHITE);input.setHintTextColor(Color.GRAY); screen.addView(input); final EditText mins=new EditText(this);mins.setHint("今天可用分钟（5–45）");mins.setInputType(2);mins.setTextColor(Color.WHITE);mins.setHintTextColor(Color.GRAY);screen.addView(mins);screen.addView(button("用离线规则压缩",v->{ if(input.getText().toString().trim().isEmpty()){toast("先写下至少一条输入");return;} showProposal(input.getText().toString(),mins.getText().toString()); }));screen.addView(button("返回",v->showHome()));}
  void showProposal(String raw,String budget){base("候选，不是承诺。"); List<String> lines=new ArrayList<>();for(String s:raw.split("\\n"))if(!s.trim().isEmpty())lines.add(s.trim());int min=12;try{min=Math.max(5,Math.min(45,Integer.parseInt(budget)));}catch(Exception e){}
    String goal=lines.get(0);String result1=lines.size()>1?lines.get(1):"完成可验证的第一步";String action="用 "+min+" 分钟完成："+result1;status.setText("OFFLINE RULES · no LLM request was made\n1 goal / max 3 outcomes / 1 action");
    EditText goalE=field("十日目标",goal), resultE=field("结果（最多三项，以；分隔）",result1), actionE=field("今日动作",action), doneE=field("完成条件", "我能看到并说明这个结果");screen.addView(goalE);screen.addView(resultE);screen.addView(actionE);screen.addView(doneE);String parked=lines.size()>2?String.join("\n",lines.subList(2,lines.size())):"（无）";screen.addView(text("PARKING LOT（未删除）\n"+parked,14));screen.addView(button("确认并交付给设备",v->deliver(goalE.getText().toString(),resultE.getText().toString(),actionE.getText().toString(),doneE.getText().toString())));screen.addView(button("返回编辑",v->showCapture()));}
  EditText field(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setTextColor(Color.WHITE);e.setHintTextColor(Color.GRAY);screen.addView(text(hint.toUpperCase(),11));return e;}
  void deliver(String goal,String results,String action,String done){ if(action.trim().isEmpty()||done.trim().isEmpty()){toast("今日动作和完成条件必须确认");return;} JSONObject offer=new JSONObject();try{offer.put("type","offer");offer.put("protocol",1);offer.put("command_id",UUID.randomUUID().toString());offer.put("cycle_id",UUID.randomUUID().toString());offer.put("revision",1);offer.put("day_index",1);offer.put("action_short",shorten(action));offer.put("done_when_short",shorten(done));offer.put("stop_at","22:00");}catch(Exception e){}
    store.edit().putString("goal",goal).putString("results",results).putString("action",action).putString("done",done).putString("offer",offer.toString()).putString("phase","PENDING_DELIVERY").apply(); boolean sent=usb.send(offer.toString()); if(!sent){store.edit().putString("phase","SIMULATED_READY").apply();toast("模拟设备已本地持久化；没有真实硬件 ACK");} else {toast("已发送真实 USB offer，等待设备 ACK");}showCycle(); }
  void showCycle(){base("TENFOLD / 当前循环");String phase=store.getString("phase","DRAFT"); status.setText(phase.startsWith("SIMULATED")?"SIMULATED DEVICE · 本地演示状态":"USB DEVICE · 设备 ACK 状态待收取");screen.addView(text("GOAL\n"+store.getString("goal",""),18));screen.addView(text("OUTCOMES\n"+store.getString("results",""),14));screen.addView(text("TODAY\n"+store.getString("action",""),20));screen.addView(text("DONE WHEN\n"+store.getString("done",""),14));boolean completed=store.getBoolean("completed",false);screen.addView(text("PROGRESS  "+(completed?"●":"○")+" ○ ○ ○ ○ ○ ○ ○ ○ ○   "+(completed?1:0)+" / 10",17));if(!completed)screen.addView(button("确认：今日完成",v->event("complete")));screen.addView(button("封存今天",v->event("seal")));screen.addView(button("恢复已有动作",v->{store.edit().putString("phase","ACTIVE").apply();toast("恢复的是已确认动作；未生成新任务");showCycle();}));screen.addView(button("回到首页",v->showHome()));}
  void event(String type){ JSONObject e=new JSONObject();try{e.put("type","event");e.put("event_type",type);e.put("seq",store.getInt("seq",0)+1);e.put("cycle_id",new JSONObject(store.getString("offer","{}")).optString("cycle_id"));}catch(Exception x){} boolean sent=usb.send(e.toString());store.edit().putInt("seq",store.getInt("seq",0)+1).putBoolean("completed",type.equals("complete")||store.getBoolean("completed",false)).putString("phase",type.equals("seal")?"SEALED":(sent?"ACTIVE":"SIMULATED_ACTIVE")).apply();toast(sent?"事件已通过 USB 发送；设备仍需持久化 ACK":"模拟事件仅保存于本机");showCycle();}
  String shorten(String s){return s.length()>24?s.substring(0,24):s;}void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
