"""Deterministic offline pixel art. Python 3 + Pillow; no network or models."""
from pathlib import Path
import json
from PIL import Image, ImageDraw, ImageFont

OUT = Path(__file__).resolve().parent
ROOT = OUT.parents[1]
COLORS = ['#000000', '#493c38', '#ffd391', '#eaa16c', '#fff0ca', '#ef9383', '#93ad89', '#d9dcc0']
NAMES = ['idle_0','idle_1','blink_0','blink_1','press_0','press_1','happy_0','happy_1','rest_0','rest_1']
def make(name):
    im = Image.new('P',(32,32),0)
    im.putpalette([v for h in COLORS for v in bytes.fromhex(h[1:])] + [0]*744)
    d = ImageDraw.Draw(im)
    state, n = name.split('_'); n = int(n)
    top, bottom = (13,26) if state=='press' else (10,25)
    if state=='happy': top-=n+1; bottom-=n+1
    if state=='idle': top-=n
    # Stepped silhouette; deliberately no smooth curves / antialiasing.
    d.rectangle((9,bottom,12,bottom+2),fill=1); d.rectangle((20,bottom,23,bottom+2),fill=1)
    d.polygon([(9,top),(22,top),(22,top+2),(25,top+2),(25,top+5),(27,top+5),(27,bottom-3),(25,bottom-3),(25,bottom),(7,bottom),(7,bottom-2),(5,bottom-2),(5,top+6),(7,top+6),(7,top+2),(9,top+2)],fill=1)
    d.polygon([(10,top+1),(21,top+1),(21,top+3),(24,top+3),(24,top+6),(26,top+6),(26,bottom-4),(24,bottom-4),(24,bottom-1),(8,bottom-1),(8,bottom-3),(6,bottom-3),(6,top+7),(8,top+7),(8,top+3),(10,top+3)],fill=2)
    d.rectangle((10,bottom-3,22,bottom-1),fill=3)
    d.rectangle((10,top+3,14,top+4),fill=4)
    # Offset sprout, two unequal leaves anchored to head.
    d.line((18,top,19,top-4),fill=1,width=1)
    d.rectangle((14,top-6,17,top-4),fill=6); d.point((13,top-6),fill=1)
    d.rectangle((19,top-7,22,top-5),fill=6); d.point((23,top-7),fill=1)
    ey = top+8
    closed = state in ('blink','rest') or (state=='press' and n==0)
    if state=='happy':
        for x in (10,20): d.line([(x,ey+1),(x+1,ey),(x+2,ey+1)],fill=1)
    elif closed:
        d.line((10,ey+1,12,ey+1),fill=1); d.line((20,ey+1,22,ey+1),fill=1)
        if state=='blink' and n==1:
            d.point((12,ey),fill=1); d.point((20,ey),fill=1)
    else:
        d.rectangle((11,ey,12,ey+2),fill=1); d.rectangle((20,ey,21,ey+2),fill=1)
    d.rectangle((8,ey+3,10,ey+3),fill=5); d.rectangle((22,ey+3,24,ey+3),fill=5)
    if state=='happy': d.rectangle((15,ey+3,17,ey+4),fill=1)
    else: d.line((15,ey+3,17,ey+3),fill=1)
    if state=='happy':
        x,y=(3,8) if n==0 else (28,6)
        d.line((x-1,y,x+1,y),fill=6); d.line((x,y-1,x,y+1),fill=6)
    if state=='rest':
        d.point((27,8-n),fill=6); d.point((29,5-n),fill=6)
    im.info['transparency']=0
    return im

def rgb565(h):
    r,g,b=bytes.fromhex(h[1:]); return ((r>>3)<<11)|((g>>2)<<5)|(b>>3)

def main():
    frames=[make(n) for n in NAMES]
    for n,im in zip(NAMES,frames): im.save(OUT/(n+'.png'),transparency=0)
    sheet=Image.new('RGB',(640,328),'#f8f0dc'); d=ImageDraw.Draw(sheet)
    for i,(n,im) in enumerate(zip(NAMES,frames)):
        x=(i%5)*128; y=(i//5)*164
        rgba=im.convert('RGBA').resize((128,128),Image.Resampling.NEAREST)
        sheet.paste(rgba,(x,y),rgba); d.text((x+12,y+140),n,fill=COLORS[1])
    sheet.save(OUT/'frames-preview.png')
    screens=[]
    for idx in (0,4,6,8):
        screen=Image.new('RGB',(240,135),'#fff0ca'); sd=ImageDraw.Draw(screen)
        sd.text((12,9),'LITTLE PAUSE',fill=COLORS[1]); sd.text((190,9),'HERE',fill=COLORS[1])
        sd.line((12,25,228,25),fill=COLORS[7])
        rgba=frames[idx].convert('RGBA').resize((96,96),Image.Resampling.NEAREST)
        screen.paste(rgba,(72,24),rgba)
        sd.text((12,119),'A: PRESS',fill=COLORS[1])
        sd.text((159,119),'B: BACK' if idx==8 else 'B: QUIET',fill=COLORS[1])
        screen.save(OUT/(NAMES[idx]+'-screen.png')); screens.append(screen)
    board=Image.new('RGB',(960,540))
    for i,s in enumerate(screens): board.paste(s.resize((480,270),Image.Resampling.NEAREST),((i%2)*480,(i//2)*270))
    board.save(OUT/'screen-preview.png')
    parts=['// Generated by design/pixel-companion/generate.py; do not edit.\n#pragma once\n#include <stdint.h>\nnamespace pet_assets {\n',
        'enum class State : uint8_t { Idle, Blink, Press, Happy, Rest };\n',
        'static constexpr uint8_t kWidth=32, kHeight=32, kFrameCount=10, kTransparent=0;\n',
        'static constexpr uint16_t kPalette[8] = {'+', '.join('0x%04x'%rgb565(c) for c in COLORS)+'};\n',
        'static constexpr uint8_t kFrames[10][1024] = {\n']
    for name,im in zip(NAMES,frames):
        pixels=list(im.get_flattened_data()); assert len(pixels)==1024 and max(pixels)<8
        parts.append('  { // '+name+'\n')
        for y in range(32): parts.append('    '+','.join(map(str,pixels[y*32:(y+1)*32]))+',\n')
        parts.append('  },\n')
    parts.append('''};
// elapsedMs is time since state entry. Press/Happy settle; other states loop.
inline uint8_t frameIndex(State state, uint32_t elapsedMs) {
  switch(state) {
    case State::Idle: return (elapsedMs / 700U) % 2U;
    case State::Blink: return 2U + ((elapsedMs / 90U) % 2U);
    case State::Press: return elapsedMs < 90U ? 4U : 5U;
    case State::Happy: return elapsedMs < 180U ? 6U : 7U;
    case State::Rest: return 8U + ((elapsedMs / 1200U) % 2U);
  }
  return 0;
}
inline uint8_t pixel(uint8_t frame, uint8_t x, uint8_t y) {
  return (frame < kFrameCount && x < kWidth && y < kHeight)
      ? kFrames[frame][static_cast<uint16_t>(y)*kWidth+x] : kTransparent;
}
} // namespace pet_assets
''')
    (ROOT/'firmware/include/pet_assets.h').write_text(''.join(parts),encoding='utf-8')
    (OUT/'palette.json').write_text(json.dumps({'colors':COLORS,'transparent':0,'format':'RGB565, logical values; no byte swapping','frames':NAMES},indent=2)+'\n')
    print('Generated 10 frames, 4 exact 240x135 screens, 2 preview boards; frame data 10240 bytes + palette 16 bytes.')

if __name__=='__main__': main()
